name: My First Workflow
on: [push]  # Trigger on every push

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
      - name: Show current date
        run: date
      - name: List current directory
        run: ls -la
  system-job:
    runs-on: ubuntu-latest
    steps:
      - name: System Info
        run: |
          echo "=== System Info ==="
          echo "Operating System: $(uname -s)"
          echo "Current User: $(whoami)"
          echo "Working Directory: $(pwd)"
      - name: Show Disk Usage
        run: |
          echo "This is a test file" > test.txt
          cat test.txt
  summary-job:
    runs-on: ubuntu-latest
    needs: [hello-job, system-job]
    steps:
      - name: Wait message
        run: echo "Both previous jobs completed successfully!"
      - name: Final summary
        run: |
          echo "=== Workflow Summary ==="
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "All jobs completed at: $(date)"