name: Workflow Events
on: [push,pull_request, workflow_dispatch]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "I've been triggered by ${{ github.event_name }} event"

