name: Event Filterskout

on:
  push:
    branches:
      - dev
      - 'release/*'
    paths-ignore:
      - 'docs/**'

jobs:
  test-filters:
    name: test filters
    runs-on: ubuntu-latest
    steps:
      - name: Demonstrate that the workflow runs only under the right conditions
        run: echo "Event filters working! Triggered on ${{ github.ref_name }} branch"
